http posts & error codes reporting
icfpcontest2020/starterkit-csharp pull request #1
Opened 2020-07-10 14:53 UTC by AndrewKostousov

2020-07-10 14:58 UTC, spaceorc requested changes

2020-07-10 14:58 UTC, spaceorc commented on run.sh
> +dotnet app.dll "$@" || echo run error code: $?
Выглядит лишним. Ведь тогда build не завершится с exit-code != 0 и сборка будет считаться успешной??

2020-07-10 14:58 UTC, spaceorc commented on build.sh
> +dotnet publish -c release -o ./build || echo build error code: $?
Может в stdErr? это >2 вроде как

2020-07-10 15:11 UTC, AndrewKostousov commented on run.sh
> +dotnet app.dll "$@" || echo run error code: $?
Отревертил

2020-07-10 15:12 UTC, AndrewKostousov commented on build.sh
> +dotnet publish -c release -o ./build || echo build error code: $?
Перенаправил

2020-07-10 21:06 UTC, beevee approved these changes

2020-07-11 06:01 UTC, AndrewKostousov commented on build.sh
> +dotnet publish -c release -o ./build || echo build error code: $?
Решили не запариваться с stderr

2020-07-11 06:02 UTC, merged